site_name: PPS Unidad1-TareaRA1-FranciscoVazquez
site_description: 'Tarea RA1 - Lavadero de Coches'
site_author: Francisco Vázquez

nav:
  - Inicio: index.md
  - '1. Trazado de Vulnerabilidad de GoAnywhere': 'TrazadoVulnerabilidadGoAnywhere/TrazadoVulnerabilidadGoAnywhere.md'
  - '2. Documentación(Ataque_SQL_FORM).': ' Documentación(Ataque_SQL_FORM)/Documentación(Ataque_SQL_FORM).md'
  - '3.Comprobación Requisitos Aplicación': 'ComprobaciónRequisitosAplicación/ComprobacionRequisitosAplicacion_Francisco.md'
  - '4. Reflexión sobre los riesgos de las aplicaciones': 'Reflexiónsobrelosriesgosdelasaplicaciones/Reflexión código.md'

docs_dir: doc

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
    - scheme: slate
      toggle:
        icon: material/weather-night

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences